2023-12-11 11:15:10,594 ERROR frappe Could not take error snapshot: No module named 'lending'
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 89, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 63, in log_error
    error_log = frappe.get_doc(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:10,599 ERROR frappe Failed to run after request hook
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 392, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1470, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1500, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-22 12:48:51,440 ERROR frappe Could not take error snapshot: (1146, "Table '_385d09b426bab63e.tabSingles' doesn't exist")
Site: klms.com
Form Dict: {'doctype': 'Loan Repayment Schedule', 'fields': '["`tabLoan Repayment Schedule`.`name`","`tabLoan Repayment Schedule`.`owner`","`tabLoan Repayment Schedule`.`creation`","`tabLoan Repayment Schedule`.`modified`","`tabLoan Repayment Schedule`.`modified_by`","`tabLoan Repayment Schedule`.`_user_tags`","`tabLoan Repayment Schedule`.`_comments`","`tabLoan Repayment Schedule`.`_assign`","`tabLoan Repayment Schedule`.`_liked_by`","`tabLoan Repayment Schedule`.`docstatus`","`tabLoan Repayment Schedule`.`idx`","`tabLoan Repayment Schedule`.`loan`","`tabLoan Repayment Schedule`.`loan_product`","`tabLoan Repayment Schedule`.`status`"]', 'filters': '[]', 'order_by': '`tabLoan Repayment Schedule`.`modified` DESC', 'start': '0', 'page_length': '20', 'view': 'List', 'group_by': '`tabLoan Repayment Schedule`.`name`', 'with_comment_count': '1', 'cmd': 'frappe.desk.reportview.get'}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1715, in call
    return fn(*args, **newargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 880, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 28, in get
    data = compress(execute(**args), args=args)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/desk/reportview.py", line 64, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/db_query.py", line 200, in execute
    result = self.build_and_run()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/db_query.py", line 240, in build_and_run
    return frappe.db.sql(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/database/database.py", line 217, in sql
    self._cursor.execute(query, values)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_385d09b426bab63e.tabLoan Repayment Schedule' doesn't exist")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/database/database.py", line 563, in get_values
    out = self._get_values_from_table(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/database/database.py", line 827, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/database/database.py", line 217, in sql
    self._cursor.execute(query, values)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_385d09b426bab63e.tabDocType' doesn't exist")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 89, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 63, in log_error
    error_log = frappe.get_doc(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 80, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, fieldname="*")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/database/database.py", line 466, in get_value
    result = self.get_values(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/database/database.py", line 583, in get_values
    out = self.get_values_from_single(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/database/database.py", line 620, in get_values_from_single
    values = self.get_singles_dict(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/database/database.py", line 666, in get_singles_dict
    queried_result = frappe.qb.get_query(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/database/database.py", line 217, in sql
    self._cursor.execute(query, values)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/sujay/lms/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table '_385d09b426bab63e.tabSingles' doesn't exist")
2023-12-26 12:06:37,947 ERROR frappe New Exception collected in error log
Site: klms.com
Form Dict: {}
2023-12-26 12:06:37,947 ERROR frappe New Exception collected in error log
Site: klms.com
Form Dict: {}
2023-12-26 12:06:37,949 ERROR frappe New Exception collected in error log
Site: klms.com
Form Dict: {}
2023-12-26 12:06:37,950 ERROR frappe New Exception collected in error log
Site: klms.com
Form Dict: {}
2023-12-26 12:06:37,949 ERROR frappe New Exception collected in error log
Site: klms.com
Form Dict: {}
2023-12-26 12:06:37,950 ERROR frappe New Exception collected in error log
Site: klms.com
Form Dict: {}
