2023-12-11 11:15:00,622 ERROR frappe Could not take error snapshot: No module named 'lending'
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 89, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 63, in log_error
    error_log = frappe.get_doc(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:00,628 ERROR frappe Failed to run after request hook
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 392, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1470, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1500, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:02,149 ERROR frappe Could not take error snapshot: No module named 'lending'
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 89, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 63, in log_error
    error_log = frappe.get_doc(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:02,154 ERROR frappe Failed to run after request hook
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 392, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1470, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1500, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:07,521 ERROR frappe Could not take error snapshot: No module named 'lending'
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 89, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 63, in log_error
    error_log = frappe.get_doc(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:07,524 ERROR frappe Failed to run after request hook
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 392, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1470, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1500, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:09,792 ERROR frappe Could not take error snapshot: No module named 'lending'
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 89, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 63, in log_error
    error_log = frappe.get_doc(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:09,795 ERROR frappe Failed to run after request hook
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 392, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1470, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1500, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:10,138 ERROR frappe Could not take error snapshot: No module named 'lending'
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 89, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 63, in log_error
    error_log = frappe.get_doc(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:10,140 ERROR frappe Failed to run after request hook
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 392, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1470, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1500, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:10,388 ERROR frappe Could not take error snapshot: No module named 'lending'
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 89, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/error.py", line 63, in log_error
    error_log = frappe.get_doc(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
2023-12-11 11:15:10,391 ERROR frappe Failed to run after request hook
Site: klms.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
    init_request(request)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
    self.set_session()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
    self.make_session(resume=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
    frappe.local.session_obj = Session(
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
    self.resume()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
    validate_ip_address(self.user)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
    frappe.get_cached_value("User", user, user_fields, as_dict=True)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1229, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1170, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1298, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
    controller = get_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 65, in get_controller
    return import_controller(doctype)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/model/base_document.py", line 87, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 37, in resolve
    resolve_redirect(self.path, request.query_string)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 107, in resolve_redirect
    redirects = frappe.get_hooks("website_redirects")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
    response = handle_exception(e)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 392, in handle_exception
    response = get_response("message", http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
    response = ErrorPage(exception=e).render()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
    super().__init__(path=path, http_status_code=http_status_code)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
    self.set_template_path()
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
    app_path = frappe.get_app_path(app)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1470, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1500, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 142, in application
    run_after_request_hooks(request, response)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/app.py", line 157, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1606, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1575, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/sujay/lms/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lending'
